// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmhfcchdhrfwzgeceoco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtaGZjY2hkaHJmd3pnZWNlb2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTAwMDQsImV4cCI6MjA2ODkyNjAwNH0.TmjVqb13sWL4VzzVfKwEX3zl1IAwH6j1EojSlfpe71o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});